schemas = [
    {
        'filename': 'llc_company.csv',
        'row_id': "index", 
        # 'id': None,
        'entity_type': "company", 
        'link_type': None,
        'name': "name",  
        'street': "records_off_street", 
        'city': "records_off_city", 
        'state': "state", 
        'postal_code': "records_off_zip", 
        'details': {},  
        'index_type': "llc_file_number",
        'index_value': "file_number",
        'is_primary': 1
}, 
    {
        'filename': 'llc_dba.csv',
        'row_id': "index", 
        # 'id': None,
        'link_type': "dba", 
        'entity_type': "company",
        'name': "llc_name",  
        'street': "", 
        'city': "", 
        'state': "", 
        'postal_code': "", 
        'details': {},  
        'index_type': "llc_file_number",
        'index_value': "file_number",
        'is_primary': 0
    },
    {
        'filename': "llc_old.csv",
        'row_id': "index", 
        # 'id': None,
        'entity_type': "company",
        'link_type': "old_name", 
        'name': "llc_name",  
        'street': "", 
        'city': "", 
        'state': "", 
        'postal_code': "", 
        'details': {},  
        'index_type': "llc_file_number",
        'index_value': "file_number",
        'is_primary': 0
    },
    {
        'filename': "llc_managers.csv",
        'row_id': "index", 
        # 'id': None,
        'entity_type': "name",
        'link_type': "manager", 
        'name': "mm_name",  
        'street': "mm_street", 
        'city': "mm_city", 
        'state': "mm_juris", 
        'postal_code': "mm_zip", 
        'details': {},  
        'index_type': "llc_file_number",
        'index_value': "file_number",
        'is_primary': 0
    }, 
    {
        'filename': "llc_agents.csv",
        'row_id': "index", 
        # 'id': None,
        'entity_type': "name",
        'link_type': "agent", 
        'name': "agent_name",  
        'street': "agent_street", 
        'city': "agent_city", 
        'state': "state", 
        'postal_code': "agent_zip", 
        'details': {},  
        'index_type': "llc_file_number",
        'index_value': "file_number",
        'is_primary': 0
    },
    {
        'filename': "corp_company.csv",
        'row_id': "index", 
        # 'id': None,
        'entity_type': "company",
        'link_type': None, 
        'name': "name",  
        'street': "", 
        'city': "", 
        'state': "", 
        'postal_code': "", 
        'details': {},  
        'index_type': "corp_file_number",
        'index_value': "file_number",
        'is_primary': 1
    }, 
    {
        'filename': "corp_officers.csv",
        'row_id': "index", 
        # 'id': None,
        'entity_type': "name",
        'link_type': 'president', 
        'name': "name",  
        'street': "street", 
        'city': "city", 
        'state': "state", 
        'postal_code': "postal_code", 
        'details': {},  
        'index_type': "corp_file_number",
        'index_value': "file_number",
        'is_primary': 0, 
        'extract_field': 'pres_name_addr'
    }, 
        {
        'filename': "corp_officers.csv",
        'row_id': "index", 
        # 'id': None,
        'entity_type': "name",
        'link_type': 'secretary', 
        'name': "name",  
        'street': "street", 
        'city': "city", 
        'state': "state", 
        'postal_code': "postal_code", 
        'details': {},  
        'index_type': "corp_file_number",
        'index_value': "file_number",
        'is_primary': 0, 
        'extract_field': 'sec_name_addr'
    }, 
    {
        'filename': "corp_agent.csv",
        'row_id': "index", 
        # 'id': None,
        'entity_type': "name",
        'link_type': 'agent', 
        'name': "agent_name",  
        'street': "agent_street", 
        'city': "agent_city", 
        'state': "state", 
        'postal_code': "agent_zip", 
        'details': {},  
        'index_type': "corp_file_number",
        'index_value': "file_number",
        'is_primary': 0
    }, 
    {
        'filename': "corp_old_names.csv",
        'row_id': "index", 
        # 'id': None,
        'entity_type': "company",
        'link_type': 'old_name', 
        'name': "assumed_old_name",  
        'street': "", 
        'city': "", 
        'state': "", 
        'postal_code': "", 
        'details': {},  
        'index_type': "corp_file_number",
        'index_value': "file_number",
        'is_primary': 0
    }, 
    {
        'filename': "candidates.csv",
        'row_id': "index", 
        # 'id': None,
        'entity_type': "name",
        'link_type': None, 
        'name': "name",  
        'street': "street", 
        'city': "city", 
        'state': "state", 
        'postal_code': "zipcode", 
        'details': {},  
        'index_type': "candidate_id",
        'index_value': "candidate_id",
        'is_primary': 1
    }, 
        {
        'filename': "committees.csv",
        'row_id': "index", 
        # 'id': None,
        'entity_type': "committee",
        'link_type': None, 
        'name': "name",  
        'street': "street", 
        'city': "city", 
        'state': "state", 
        'postal_code': "zipcode", 
        'details': {"party": "party", "purpose": "purpose"},  
        'index_type': "committee_id",
        'index_value': "committee_id",
        'is_primary': 1
    }, 
    {
        'filename': "receipts.csv",
        'row_id': "index", 
        # 'id': None,
        'entity_type': "name",
        'link_type': "donation", 
        'name': "name",  
        'street': "street", 
        'city': "city", 
        'state': "state", 
        'postal_code': "zipcode", 
        'details': {"amount": "amount"},  
        'index_type': "committee_id",
        'index_value': "committee_id",
        'is_primary': 0
    }, 
    {
        'filename': "receipts.csv",
        'row_id': "index", 
        # 'id': None,
        'entity_type': "donor",
        'link_type': None, 
        'name': "name",  
        'street': "street", 
        'city': "city", 
        'state': "state", 
        'postal_code': "zipcode", 
        'details': {},  
        'index_type': "donation_id",
        'index_value': "donation_id",
        'is_primary': 1
    }, 
    {
        'filename': "receipts.csv",
        'row_id': "index", 
        # 'id': None,
        'entity_type': "company",
        'link_type': "employs", 
        'name': "vendor_name",  
        'street': "vendor_street", 
        'city': "vendor_city", 
        'state': "vendor_state", 
        'postal_code': "vendor_zipcode", 
        'details': {},  
        'index_type': "donation_id",
        'index_value': "donation_id",
        'is_primary': 0
    }, 
    {
        'filename': "contracts.csv",
        'row_id': "index", 
        # 'id': None,
        'entity_type': "contract",
        'link_type': None, 
        'name': "contract_revision",  
        'street': "", 
        'city': "", 
        'state': "", 
        'postal_code': "", 
        'details': {
            "purchase_order_description": "purchase_order_description", 
            "award_amount": "award_amount", 
            "start_date": "start_date", 
            "end_date": "end_date", 
            "approval_date": "approval_date"
        },  
        'index_type': "contract_number",
        'index_value': "contract_revision",
        'is_primary': 1
    }, 
    {
        'filename': "contracts.csv",
        'row_id': "index", 
        # 'id': None,
        'entity_type': "company",
        'link_type': "contract", 
        'name': "vendor_name",  
        'street': "vendor_street", 
        'city': "city", 
        'state': "state", 
        'postal_code': "zip", 
        'details': {
            "purchase_order_description": "purchase_order_description", 
            "award_amount": "award_amount", 
            "start_date": "start_date", 
            "end_date": "end_date", 
            "approval_date": "approval_date"
        },  
        'index_type': "contract_number",
        'index_value': "contract_revision",
        'is_primary': 0
    }, 
    {
        'filename': "contracts.csv",
        'row_id': "index", 
        # 'id': None,
        'entity_type': "department",
        'link_type': "contract", 
        'name': "department",  
        'street': "", 
        'city': "", 
        'state': "", 
        'postal_code': "", 
        'details': {
            "award_amount": "award_amount"
        },  
        'index_type': "contract_number",
        'index_value': "contract_revision",
        'is_primary': 0
    }
]