# This is a basic workflow to help you get started with Actions

name: Update Database

concurrency: 
  group: database-build


# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: setup requirementss
        run: pip install -r requirements.txt

      # Runs a single command using the runners shell
      - name: build database
        run: make
 
      - name: release
        uses: WebFreak001/deploy-nightly@v3.1.0
        with:
          upload_url: "https://uploads.github.com/repos/anthonymoser/deseguys_db/releases/148069291/assets{?name,label}"
          release_id: 148069291
          asset_path: ./combined.zip # path to archive to upload
          asset_name: combined.zip # name to upload the release as, use $$ to insert date (YYYYMMDD) and 6 letter commit hash
          asset_content_type: application/zip # required by GitHub API
          max_releases: 7 # optional, if there are more releases than this matching the asset_name, the oldest ones are going to be deleted
          
         
      - name: keepalive
        uses: gautamkrishnar/keepalive-workflow@v1
